In [1]:
import numpy as np
# import matplotlib.pyplot as plt
# from sklearn.model_selection import train_test_split
# import math
from scipy.io.arff import loadarff
import pandas as pd

C:\Users\prusak.patryk\AppData\Local\Temp\ipykernel_20628\2646969198.py:6: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


#### 9 different datasets for classification with binary classes and numerical variables
1. 3 small datasets containing at most 10 variables
2. 6 large datasets containing more than 10 variables

In [6]:
# Perform a small EDA of the datasets, check for missing values, print summary, add some short dataset description
raw_data = loadarff("./Datasets/blood-transfusion-service-center.arff")
df_data = pd.DataFrame(raw_data[0])
df_no_class=df_data.drop('Class',axis=1)
X = df_no_class.to_numpy()
y = df_data['Class'].to_numpy()

print(X)
print(y)

[[2.00e+00 5.00e+01 1.25e+04 9.80e+01]
 [0.00e+00 1.30e+01 3.25e+03 2.80e+01]
 [1.00e+00 1.60e+01 4.00e+03 3.50e+01]
 ...
 [2.30e+01 3.00e+00 7.50e+02 6.20e+01]
 [3.90e+01 1.00e+00 2.50e+02 3.90e+01]
 [7.20e+01 1.00e+00 2.50e+02 7.20e+01]]
[b'2' b'2' b'2' b'2' b'1' b'1' b'2' b'1' b'2' b'2' b'1' b'1' b'2' b'1'
 b'2' b'2' b'2' b'2' b'2' b'2' b'2' b'1' b'2' b'2' b'1' b'1' b'1' b'2'
 b'2' b'1' b'1' b'2' b'2' b'2' b'1' b'2' b'2' b'2' b'2' b'2' b'2' b'1'
 b'2' b'1' b'2' b'2' b'1' b'1' b'1' b'1' b'1' b'2' b'1' b'1' b'2' b'2'
 b'2' b'2' b'1' b'1' b'1' b'2' b'1' b'2' b'2' b'1' b'2' b'1' b'1' b'1'
 b'1' b'1' b'2' b'1' b'2' b'2' b'2' b'1' b'1' b'1' b'2' b'1' b'1' b'1'
 b'2' b'1' b'1' b'1' b'1' b'2' b'2' b'1' b'1' b'1' b'1' b'1' b'1' b'2'
 b'2' b'2' b'2' b'2' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'2' b'1'
 b'1' b'2' b'1' b'1' b'2' b'1' b'1' b'2' b'2' b'2' b'2' b'2' b'1' b'1'
 b'2' b'1' b'2' b'2' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'2' b'2' b'1' b'1' b'2' b'1'

#### Datasets preparation for logistic regression including:
1. Filling in missing values (less than 10% of missing values per variable)
2. Removing colinear variables

In [ ]:
# Fill in missing values for each dataset


In [ ]:
# Remove colinear variables from each dataset

#### Optimization algorithms with default recommended parameters, additionaly each algorithm has an option to include interactions between variables
1. IWLS
2. SGD
3. ADAM

In [ ]:
# Implement optimization algorithms